CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE ACTIVITY (
    ACTIVITY_ID NUMBER PRIMARY KEY,
    ACTIVITY_NAME VARCHAR2(50),
    CATEGORY_ID NUMBER NOT NULL,
    CONSTRAINT FK_ACTIVITY_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE SUB_ACTIVITY (
    SUBACTIVITY_ID NUMBER PRIMARY KEY,
    SUBACTIVITY_NAME VARCHAR2(100) NOT NULL,
    ACTIVITY_ID NUMBER NOT NULL,
    CONSTRAINT FK_SUBACTIVITY_ACTIVITY
        FOREIGN KEY (ACTIVITY_ID)
        REFERENCES ACTIVITY(ACTIVITY_ID)
);

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(50)
);

CREATE TABLE SCHEDULE (
    SCHEDULE_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    ACTIVITY_ID NUMBER,
    SUBACTIVITY_ID NUMBER,
    SCHEDULE_DATE DATE,
    PLANNED_HOURS NUMBER(4,2),

    CONSTRAINT FK_SCHEDULE_STUDENT
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CONSTRAINT FK_SCHEDULE_ACTIVITY
        FOREIGN KEY (ACTIVITY_ID)
        REFERENCES ACTIVITY(ACTIVITY_ID),

    CONSTRAINT FK_SCHEDULE_SUBACTIVITY
        FOREIGN KEY (SUBACTIVITY_ID)
        REFERENCES SUB_ACTIVITY(SUBACTIVITY_ID)
);

CREATE TABLE DAILY_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    ACTIVITY_ID NUMBER,
    SUBACTIVITY_ID NUMBER,
    LOG_DATE DATE,
    HOURS_SPENT NUMBER(4,2),

    CONSTRAINT FK_DAILYLOG_STUDENT
        FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CONSTRAINT FK_DAILYLOG_ACTIVITY
        FOREIGN KEY (ACTIVITY_ID)
        REFERENCES ACTIVITY(ACTIVITY_ID),

    CONSTRAINT FK_DAILYLOG_SUBACTIVITY
        FOREIGN KEY (SUBACTIVITY_ID)
        REFERENCES SUB_ACTIVITY(SUBACTIVITY_ID)
);
